# Generated by Django 4.2.4 on 2023-11-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(default='', max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.area')),
            ],
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('celular', models.IntegerField()),
                ('empresa', models.CharField(max_length=255)),
                ('tipo_equipo', models.CharField(blank=True, choices=[('', 'Seleccione un Equipo'), ('Portatil', 'Portatil'), ('Disco Duro', 'Disco Duro'), ('Tablet', 'Tablet')], max_length=25, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ingreso')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.area')),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Salida')),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.visitantes')),
            ],
        ),
    ]
