# Generated by Django 4.2.4 on 2023-11-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('celular', models.IntegerField()),
                ('empresa', models.CharField(max_length=255)),
                ('tipo_equipo', models.CharField(blank=True, choices=[[0, 'Disco Duro'], [1, 'Tablet'], [2, 'Portatil']], max_length=25, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ingreso')),
                ('area_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.area')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.empleado')),
            ],
        ),
    ]
