# Generated by Django 4.2.4 on 2023-11-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_activo',
        ),
    ]
