# Generated by Django 4.2.4 on 2023-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0007_alter_visitantes_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('0', 'Portatil'), ('1', 'Disco Duro'), ('2', 'Tablet')], max_length=25, null=True),
        ),
    ]
