# Generated by Django 4.2.4 on 2023-11-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0008_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
