# Generated by Django 4.2.4 on 2023-11-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0009_alter_visitantes_tipo_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantes',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='visitantes',
            old_name='area_visita',
            new_name='area_id',
        ),
        migrations.RenameField(
            model_name='visitantes',
            old_name='empleado',
            new_name='empleado_id',
        ),
        migrations.RenameField(
            model_name='visitantes',
            old_name='cedula',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='visitantes',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
