# Generated by Django 4.2.4 on 2023-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0010_rename_apellido_visitantes_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('', 'Seleccione un Equipo'), ('Portatil', 'Portatil'), ('Disco Duro', 'Disco Duro'), ('Tablet', 'Tablet')], max_length=25, null=True),
        ),
    ]
