# Generated by Django 4.2.4 on 2023-11-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0010_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administracion',
            new_name='is_staff',
        ),
    ]
