# Generated by Django 4.2.4 on 2023-11-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0011_alter_visitantes_tipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='', max_length=255),
        ),
    ]
