# Generated by Django 4.2.4 on 2023-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0012_empleado_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
