# Generated by Django 4.2.4 on 2023-11-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_app', '0013_alter_visitantes_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Salida')),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edificio_app.visitantes')),
            ],
        ),
    ]
